name: Dummy commit if someone else than sysadmin@cims.carleton.ca

on:
  push:
    branches:
      - main

jobs:
  enforce-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit email
        id: get_email
        run: |
          email=$(git log -1 --pretty=format:'%ae')
          echo "Commit email: $email"
          echo "email=$email" >> $GITHUB_ENV

      - name: Check email and perform dummy commit if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ env.email }}
        run: |
          if [ "${{ env.EMAIL }}" != "sysadmin@cims.carleton.ca" ]; then
            echo "Email does not match. Performing dummy commit."
            git config user.name "cimslab"
            git config user.email "sysadmin@cims.carleton.ca"
            echo "Dummy commit at $(date)" > dummyfile.txt
            git add dummyfile.txt
            git commit -m "Dummy commit to deploy"
            git push
          else
            echo "Email matches. No action needed."
          fi
